name: generating a ascii key

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: excuting the shell
          run: |
            chmod +x shell-script.sh
            ./shell-script.sh