name: generating a ascii key

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: list the file
          run: ls -ltra  

        - name: excuting the shell
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh